platform :ios, '8.2'

inhibit_all_warnings!

target 'ColorfulWoodNetWork' do

pod 'AFNetworking',       '~> 3.2.1'
pod 'RealReachability',   '~> 1.2.0'
pod 'JSONModel',          '~> 1.7.0'
pod 'ColorfulWoodSystem'
pod 'ColorfulWoodTools'


end
